### PR TITLE
Fix for compiling on Windows

### PR DESCRIPTION
**Pull request by roymacdonald**
Just a very simple fix to be able to use in windows.

### CODE REVIEW

**Comment by arturoc** [comment]
roy, the tests for this in windows are currently passing without problem but failing with your change.

**Comment by roymacdonald** [comment]
ha. sorry. that was  a sloppy PR. I was a bit sleepy. There was a typo error.
Although, I'm curious,  without this fix, were the tests passing for windows? because I am unable to compile without this fix on VS2017 win10, both 32 and 64 bits.

**Comment by roymacdonald** [comment]
Now it is passing the tests.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
